openapi: 3.0.3
info:
  title: MyRoad
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8009'
paths:
  /api/v1/login:
    post:
      summary: Login
      operationId: login
      description: 'Authenticates a user and returns an API token'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid login details'
                properties:
                  message:
                    type: string
                    example: 'Invalid login details'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'The email of the user.<br>Use editor/admin@example.com for different permissions<br>'
                  example: admin@example.com
                password:
                  type: string
                  description: 'The password of the user.'
                  example: password
              required:
                - email
                - password
      security: []
  /api/v1/admin/tours:
    post:
      summary: 'Store a new Tour'
      operationId: storeANewTour
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  data:
                    id: 9b20f8e0-b615-4090-8702-e8bf7adedc82
                    travelId: 4f4bd032-e7d4-402a-bdf6-aaf6be240d53
                    name: ITICE20211107
                    startingDate: '2021-11-07'
                    endingDate: '2021-11-15'
                    price: 213
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 9b20f8e0-b615-4090-8702-e8bf7adedc82
                      travelId:
                        type: string
                        example: 4f4bd032-e7d4-402a-bdf6-aaf6be240d53
                      name:
                        type: string
                        example: ITICE20211107
                      startingDate:
                        type: string
                        example: '2021-11-07'
                      endingDate:
                        type: string
                        example: '2021-11-15'
                      price:
                        type: integer
                        example: 213
      tags:
        - 'Tour Endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                travelId:
                  type: string
                  description: 'The id of the travel.'
                  example: cbf304ae-a335-43fa-9e56-811612dcb601
                startingDate:
                  type: string
                  description: 'The starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
                  example: '2024-01-01'
                endingDate:
                  type: string
                  description: 'The ending date of the tour. Must be a valid date in the format <code>Y-m-d</code>. Must be a date after <code>startingDate</code>.'
                  example: '2024-01-08'
                price:
                  type: integer
                  description: 'The price of the tour. Must be at least 1.'
                  example: 1000
              required:
                - travelId
                - startingDate
                - endingDate
                - price
  '/api/v1/travel/{travel_slug}/tours':
    get:
      summary: 'Get tours by travel slug'
      operationId: getToursByTravelSlug
      description: ''
      parameters:
        -
          in: query
          name: priceFrom
          description: 'The minimum price of the tour.'
          example: 100.0
          required: false
          schema:
            type: number
            description: 'The minimum price of the tour.'
            example: 100.0
        -
          in: query
          name: priceTo
          description: 'The maximum price of the tour.'
          example: 10000.0
          required: false
          schema:
            type: number
            description: 'The maximum price of the tour.'
            example: 10000.0
        -
          in: query
          name: dateFrom
          description: 'The minimum starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
          example: '2024-01-01'
          required: false
          schema:
            type: string
            description: 'The minimum starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
            example: '2024-01-01'
        -
          in: query
          name: dateTo
          description: 'The maximum starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
          example: '2024-12-31'
          required: false
          schema:
            type: string
            description: 'The maximum starting date of the tour. Must be a valid date in the format <code>Y-m-d</code>.'
            example: '2024-12-31'
        -
          in: query
          name: sortBy
          description: 'The field to sort by.'
          example: price
          required: false
          schema:
            type: string
            description: 'The field to sort by.'
            example: price
            enum:
              - price
        -
          in: query
          name: sortOrder
          description: 'The order to sort by.'
          example: asc
          required: false
          schema:
            type: string
            description: 'The order to sort by.'
            example: asc
            enum:
              - asc
              - desc
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 7f0ff8cc-6b19-407e-9915-279ad76c0b5c
                      travelId: cbf304ae-a335-43fa-9e56-811612dcb601
                      name: ITUNI20240112
                      startingDate: '2024-01-12'
                      endingDate: '2024-01-20'
                      price: 1899
                    -
                      id: 90155d92-01e5-4c4b-a5a8-e24011fa8418
                      travelId: cbf304ae-a335-43fa-9e56-811612dcb601
                      name: ITUNI20240121
                      startingDate: '2024-01-21'
                      endingDate: '2024-01-28'
                      price: 1899
                  links:
                    first: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?sortBy=price&sortOrder=desc&priceFrom=10&page=1'
                    last: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?sortBy=price&sortOrder=desc&priceFrom=10&page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?sortBy=price&sortOrder=desc&priceFrom=10&page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours'
                    per_page: 2
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 7f0ff8cc-6b19-407e-9915-279ad76c0b5c
                        travelId: cbf304ae-a335-43fa-9e56-811612dcb601
                        name: ITUNI20240112
                        startingDate: '2024-01-12'
                        endingDate: '2024-01-20'
                        price: 1899
                      -
                        id: 90155d92-01e5-4c4b-a5a8-e24011fa8418
                        travelId: cbf304ae-a335-43fa-9e56-811612dcb601
                        name: ITUNI20240121
                        startingDate: '2024-01-21'
                        endingDate: '2024-01-28'
                        price: 1899
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 7f0ff8cc-6b19-407e-9915-279ad76c0b5c
                        travelId:
                          type: string
                          example: cbf304ae-a335-43fa-9e56-811612dcb601
                        name:
                          type: string
                          example: ITUNI20240112
                        startingDate:
                          type: string
                          example: '2024-01-12'
                        endingDate:
                          type: string
                          example: '2024-01-20'
                        price:
                          type: integer
                          example: 1899
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        example: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?sortBy=price&sortOrder=desc&priceFrom=10&page=1'
                      last:
                        type: string
                        example: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?sortBy=price&sortOrder=desc&priceFrom=10&page=1'
                      prev:
                        type: string
                        example: null
                      next:
                        type: string
                        example: null
                  meta:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      from:
                        type: integer
                        example: 1
                      last_page:
                        type: integer
                        example: 1
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours?sortBy=price&sortOrder=desc&priceFrom=10&page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      path:
                        type: string
                        example: 'http://localhost:8009/api/v1/travel/united-arab-emirates-from-dubai-to-abu-dhabi/tours'
                      per_page:
                        type: integer
                        example: 2
                      to:
                        type: integer
                        example: 2
                      total:
                        type: integer
                        example: 2
      tags:
        - 'Tour Endpoints'
    parameters:
      -
        in: path
        name: travel_slug
        description: 'The slug of the travel.'
        example: united-arab-emirates-from-dubai-to-abu-dhabi
        required: true
        schema:
          type: string
  /api/v1/admin/travels:
    post:
      summary: 'Store a new Travel'
      operationId: storeANewTravel
      description: 'Create a new travel'
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  data:
                    id: 9b20f41b-0c51-4cc1-aa08-5c076876b356
                    name: 'new trrascve'
                    slug: new-trrascve-9
                    description: 'new descriptrioin asdkj haskjdh jaksd'
                    numberOfDays: 4
                    numberOfNight: 3
                    moods:
                      nature: 80
                      relax: 20
                      history: 90
                      culture: 30
                      party: 10
                    images:
                      -
                        url: 'http://localhost:8009/storage/9/Screenshot-2024-01-16-alle-13.01.46.png'
                        name: 'Screenshot 2024-01-16 alle 13.01.46'
                        size: 170087
                        mime_type: image/png
                      -
                        url: 'http://localhost:8009/storage/10/Screenshot-2023-12-07-alle-16.10.03.png'
                        name: 'Screenshot 2023-12-07 alle 16.10.03'
                        size: 88690
                        mime_type: image/png
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 9b20f41b-0c51-4cc1-aa08-5c076876b356
                      name:
                        type: string
                        example: 'new trrascve'
                      slug:
                        type: string
                        example: new-trrascve-9
                      description:
                        type: string
                        example: 'new descriptrioin asdkj haskjdh jaksd'
                      numberOfDays:
                        type: integer
                        example: 4
                      numberOfNight:
                        type: integer
                        example: 3
                      moods:
                        type: object
                        properties:
                          nature:
                            type: integer
                            example: 80
                          relax:
                            type: integer
                            example: 20
                          history:
                            type: integer
                            example: 90
                          culture:
                            type: integer
                            example: 30
                          party:
                            type: integer
                            example: 10
                      images:
                        type: array
                        example:
                          -
                            url: 'http://localhost:8009/storage/9/Screenshot-2024-01-16-alle-13.01.46.png'
                            name: 'Screenshot 2024-01-16 alle 13.01.46'
                            size: 170087
                            mime_type: image/png
                          -
                            url: 'http://localhost:8009/storage/10/Screenshot-2023-12-07-alle-16.10.03.png'
                            name: 'Screenshot 2023-12-07 alle 16.10.03'
                            size: 88690
                            mime_type: image/png
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: 'http://localhost:8009/storage/9/Screenshot-2024-01-16-alle-13.01.46.png'
                            name:
                              type: string
                              example: 'Screenshot 2024-01-16 alle 13.01.46'
                            size:
                              type: integer
                              example: 170087
                            mime_type:
                              type: string
                              example: image/png
      tags:
        - 'Travel Endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the travel. Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: 'Jordan 361'
                description:
                  type: string
                  description: 'The description of the travel. Must be at least 2 characters. Must not be greater than 2000 characters.'
                  example: 'Jordan 361°: the perfect tour to....'
                numberOfDays:
                  type: integer
                  description: 'The number of days of the travel. Must be at least 1. Must not be greater than 1000.'
                  example: 5
                visibility:
                  type: string
                  description: 'The visibility of the travel (public or private).'
                  example: public
                  enum:
                    - public
                    - private
                moods:
                  type: string
                  description: 'The moods of the travel.'
                  example: "{'nature': 80,'relax': 20,'history': 90,'culture': 30,'party': 10}"
                images:
                  type: array
                  description: 'List of file.'
                  items:
                    type: string
                    format: binary
              required:
                - name
                - description
                - numberOfDays
                - visibility
                - moods
  '/api/v1/admin/travels/{id}':
    put:
      summary: 'Update a Travel'
      operationId: updateATravel
      description: 'Update a travel'
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  data:
                    id: 9b20f41b-0c51-4cc1-aa08-5c076876b356
                    name: 'new trrascve'
                    slug: new-trrascve-9
                    description: 'new descriptrioin asdkj haskjdh jaksd'
                    numberOfDays: 4
                    numberOfNight: 3
                    moods:
                      nature: 80
                      relax: 20
                      history: 90
                      culture: 30
                      party: 10
                    images:
                      -
                        url: 'http://localhost:8009/storage/9/Screenshot-2024-01-16-alle-13.01.46.png'
                        name: 'Screenshot 2024-01-16 alle 13.01.46'
                        size: 170087
                        mime_type: image/png
                      -
                        url: 'http://localhost:8009/storage/10/Screenshot-2023-12-07-alle-16.10.03.png'
                        name: 'Screenshot 2023-12-07 alle 16.10.03'
                        size: 88690
                        mime_type: image/png
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: 9b20f41b-0c51-4cc1-aa08-5c076876b356
                      name:
                        type: string
                        example: 'new trrascve'
                      slug:
                        type: string
                        example: new-trrascve-9
                      description:
                        type: string
                        example: 'new descriptrioin asdkj haskjdh jaksd'
                      numberOfDays:
                        type: integer
                        example: 4
                      numberOfNight:
                        type: integer
                        example: 3
                      moods:
                        type: object
                        properties:
                          nature:
                            type: integer
                            example: 80
                          relax:
                            type: integer
                            example: 20
                          history:
                            type: integer
                            example: 90
                          culture:
                            type: integer
                            example: 30
                          party:
                            type: integer
                            example: 10
                      images:
                        type: array
                        example:
                          -
                            url: 'http://localhost:8009/storage/9/Screenshot-2024-01-16-alle-13.01.46.png'
                            name: 'Screenshot 2024-01-16 alle 13.01.46'
                            size: 170087
                            mime_type: image/png
                          -
                            url: 'http://localhost:8009/storage/10/Screenshot-2023-12-07-alle-16.10.03.png'
                            name: 'Screenshot 2023-12-07 alle 16.10.03'
                            size: 88690
                            mime_type: image/png
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: 'http://localhost:8009/storage/9/Screenshot-2024-01-16-alle-13.01.46.png'
                            name:
                              type: string
                              example: 'Screenshot 2024-01-16 alle 13.01.46'
                            size:
                              type: integer
                              example: 170087
                            mime_type:
                              type: string
                              example: image/png
      tags:
        - 'Travel Endpoints'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the travel. Must be at least 2 characters. Must not be greater than 255 characters.'
                  example: 'Jordan 361'
                description:
                  type: string
                  description: 'The description of the travel. Must be at least 2 characters. Must not be greater than 2000 characters.'
                  example: 'Jordan 361°: the perfect tour to....'
                numberOfDays:
                  type: integer
                  description: 'The number of days of the travel. Must be at least 1. Must not be greater than 1000.'
                  example: 5
                visibility:
                  type: string
                  description: 'The visibility of the travel (public or private).'
                  example: public
                  enum:
                    - public
                    - private
                moods:
                  type: string
                  description: 'The moods of the travel.'
                  example: "{'nature': 80,'relax': 20,'history': 90,'culture': 30,'party': 10}"
                images:
                  type: array
                  description: 'List of file. It will replace all the existing images'
                  items:
                    type: string
                    format: binary
              required:
                - name
                - description
                - numberOfDays
                - visibility
                - moods
    parameters:
      -
        in: path
        name: id
        description: 'Optional parameter. uuid required The ID of the travel.<br>'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: d408be33-aa6a-4c73-a2c8-58a70ab2ba4d
tags:
  -
    name: Authentication
    description: "\nAPIs for user authentication"
  -
    name: 'Tour Endpoints'
    description: ''
  -
    name: 'Travel Endpoints'
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by login endpoint.'
security:
  -
    default: []
